
 meta_product_name: "EcoTracker"
 meta_title: "EcoTracker - Reduce Your Carbon Footprint"
 meta_description: "EcoTracker tracks and reduces your daily carbon footprint. Be an eco-hero!"
 meta_image: "cover.png"
